comment:
  layout: header, changes, diff
  
coverage:
  precision: 2
  round: nearest
  
  ignore:
  - tests/.*
  - examples/.*
  
  status:
    patch: false
    
  parsers:
    gcov:
      branch_detection:
        macro: no
        conditional: no
        loops: no
