os: linux
sudo: required
dist: trusty

language:
  - c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavl-dev libev-dev valgrind swig python-dev
  - pip install --user codecov
  
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - cd cmocka
  - mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j2 && sudo make install
  - cd ../..
  
  - git clone https://github.com/CESNET/libyang.git
  - cd libyang; mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make -j2 && sudo make install
  - cd ../..
  
  - git clone https://github.com/google/protobuf.git
  - cd protobuf
  - ./autogen.sh && ./configure --prefix=/usr && make -j2 && sudo make install
  - cd ..
  
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - cd protobuf-c
  - ./autogen.sh && ./configure --prefix=/usr && make -j2 && sudo make install
  - cd ..

script:
  - mkdir build ; cd build ; cmake -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_FLAGS="-Werror -coverage" .. && make -j2
  - ctest --output-on-failure
  - sudo ctest --output-on-failure --tests-regex ac_test

after_success:
  - if [ "$CC" = "gcc" ]; then codecov; fi

env:
  global:
   # COVERITY_SCAN_TOKEN
   - secure: "dV/BjJUU5YLYVJk58qmbKjUoORZ7ipQzmMVsqGAgcNzpPxsYyL7c6+vvLhNPNE4oiYEUvB9f2yIE+gu6Tt1BIlm2lVzPfR4E9ArOhufzJ+8VYwYj9P9m9vZTL433t5RG4dyVVxCgo6HG7Sebp5qF4gH+bpwdFiKS2lvtwJ0h3zAMVALoE0nZDhiykrJfRpKfpb2qiWqxaxFK9syn2hwb7oOWQlBj2q21EJXUY4aPcK6a5SHfAORKcGl49Z7qR46GGpv9YKVqlNqyczRQB2krKPiHtVU0QdwI+7snG2sDYU8sOqZ5ppFuzXiARkYSuqHufnZYn0w4U2F7MIIXg8rIBh1r3NOAbM8bAlRGWKx+qptNBdHKzdkrzJFhRVOEE9wi9YhvY2IqtPLxQ1HUMeqsDXM+Vk1ZkzwSw1dIHMPWzb4pKKnoIaDZppxYZVx84lHVO7oceJ7zLwv/x/l+4MyHbqz1OXsGE8IxVMGlJSVT7TnmQd5bQ80Jc3tT4nWbqFEy6KRpCwhvvTR8z0RsSECc6V9+rDATYFWWzfZxl/zLB8tKOkiaPjH/C1Hmq8Om58wZ+PHaJKnkwMcT24iCXpi3sjyHWDlgUUdekJBVPUchyIqIcXEsKE6pFsbr5USyZFX+mD8p8+r14KRiW8nJRoVxB3EktSXiHvXFU8E4Qo6uJKs="

addons:
  coverity_scan:
    project:
      name: "sysrepo/sysrepo"
    notification_email: raszabo@cisco.com
    build_command_prepend: "mkdir build ; cd build ; cmake .. && make clean"
    build_command:   "make -j 2"
    branch_pattern: coverity
