os: linux
sudo: required
dist: trusty

language: 
  - c

compiler: 
  - gcc
  - clang
  
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavl-dev valgrind
  - pip install --user codecov
  
  - wget http://mirrors.kernel.org/ubuntu/pool/main/p/protobuf/libprotobuf9_2.6.1-1_amd64.deb
  - sudo dpkg -i --force-depends libprotobuf9_2.6.1-1_amd64.deb
  
  - git clone git://git.cryptomilk.org/projects/cmocka.git
  - cd cmocka
  - git checkout tags/cmocka-1.0.1
  - mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ..
  - make -j2 && sudo make install
  - cd ../..
  
  - git clone https://github.com/CESNET/libyang.git
  - cd libyang; mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr -DCMAKE_BUILD_TYPE=Release ..
  - make -j2 && sudo make install
  - cd ../..
  

  
  - git clone https://github.com/protobuf-c/protobuf-c.git
  - cd protobuf-c
  - ./autogen.sh && ./configure --prefix=/usr && make -j2 && sudo make install
  - cd ..

script: 
  - mkdir build && cd build && cmake .. && make -j2 && ctest

after_success:
  - if [ "$CC" = "gcc" ]; then codecov; fi
