language: c

compiler:
  - clang

os:
  - linux

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y libavl-dev
  
  - wget https://cmocka.org/files/1.0/cmocka-1.0.1.tar.xz
  - tar -xJvf cmocka-1.0.1.tar.xz
  - cd cmocka-1.0.1 && mkdir build && cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - sudo make install
  - cd ../..
  
  - git clone https://github.com/CESNET/libyang.git
  - cd libyang; mkdir build; cd build
  - cmake -DCMAKE_INSTALL_PREFIX:PATH=/usr ..
  - make
  - make install
  - cd ../..

script: cmake . && make && make test
